analytics.integration.enable=true
analytics.onpremise.enable=false
analytics.project={"id"\:3565430,"name"\:"Cellphone Shop Trial \#3565430","teamId"\:3579128,"status"\:null,"gitRepositories"\:null,"team"\:null,"organizationId"\:3552519,"accountId"\:null,"sampleProject"\:false,"autoIntegrate"\:false}
analytics.team={"id"\:3579128,"role"\:null,"name"\:null,"organization"\:null}
analytics.testcloud.integration.enable=true
analytics.testreport.autoupload.enable=true
analytics.testreport.autoupload.manualstop.enable=true
