<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_demo_password_label</name>
   <tag></tag>
   <elementGuidId>f4cf16c2-f3a2-4745-89e3-ad84c47b04c8</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#demo_password_label</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//*[@id = 'demo_password_label']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>#demo_password_label</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>dcf58964-feb0-41d1-bde2-5c3d621f8303</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-group-addon</value>
      <webElementGuid>1e2f93af-b99a-4c18-b962-12045a5a02b6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>demo_password_label</value>
      <webElementGuid>a3b42119-6809-41e6-960b-5f2ee5f6c538</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>parent</name>
      <type>Main</type>
      <value>md5.v1-73863efb30675236b96848c302e4a90f</value>
      <webElementGuid>8841dbf9-4698-4bc6-a9b7-b45619ea4bf4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//*[@id = 'demo_password_label']</value>
      <webElementGuid>4e35870f-a4d6-4bcd-a7bf-2c1a5f77e3ec</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//*[@id = 'demo_password_label']</value>
      <webElementGuid>53f76cb9-cf6d-43f3-b47b-ba87024831e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[@id = 'demo_password_label']</value>
      <webElementGuid>3dc58677-205c-461d-b140-dc2ad00e6520</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
